### ISSUE TITLE
Update repo configs from https://getscaffold.dev/

### ISSUE THREAD

**Issue by AlexSkrypnyk** [AlexSkrypnyk/shellvar#17]
Download the latest code from Scaffold repo (actual code, not the release).

- Update `composer.json` with the structure from Scaffold. Preserve the values of the existing fields, but order the fields as per Scaffold's `composer.json`. Add missing fields.
- Update the Symfony command to use the file structure of `CLI Command` from the scaffold repo.
- Update tests to use new traits from Scaffold instead of a `HelperTrait.php`. Use only traits that are required.
- Update CI to run with coverage
- Add Renovate config from Scaffold
- Add/update all GitHub actions and configs to be per Scaffold
- Update readme to use the structure from Scaffold, including the generated logo (circle). Transfer the usage examples into the readme structure from Scaffold
- Update Box config
- Add PHPStan config and fix all newly found violations

- Do not create `docs` folder and CI action - this project is too small to have extensive docs.

Make sure that CI passes.

**Comment by lankmiler** [comment]
@AlexSkrypnyk Can you explain more about 2 point. Or give maybe some kind of example. And also there is a lot of issues related to phpstan(185), do we need to fix them all?

**Comment by AlexSkrypnyk** [comment]
@lankmiler 
Re 2 - please see https://getscaffold.dev/php/cli-command.html

just need to update the code structure to reflect what is in the scaffold - the command loader , app loader, src, tests

re phpstan - please fix all violations
