### ISSUE TITLE
Update Readme to include documentation about 'lint' command.

### ISSUE THREAD

**Issue by AlexSkrypnyk** [AlexSkrypnyk/shellvar#42]
Add docs with example on how to use `lint` and `extract` commands.

**Comment by AlexSkrypnyk** [comment]
Once implemented, @AlexSkrypnyk  will action https://github.com/AlexSkrypnyk/shell-var-lint/issues/12

**Comment by tannguyen04** [comment]
Hi @AlexSkrypnyk 
I can see you added example how to use `extract` command.
Could you please confirm that I just need to add only example with `lint` command ?

**Comment by AlexSkrypnyk** [comment]
@tannguyen04 
yes, please add for `lint` command so that we have documentation for both commands.
